import matplotlib.pyplot as plt
from resources import getCityInfo
from numpy import mean

def simulateSolarPanels(city_name, numberOfpanels, totalSurfaceArea,OptToPlot):

    ''' Takes in the city name, number of panels, total surface area of the panels being used and the choice of the user
        if they want to plot how the solar irradience of the city if their choice has been over the previous 4 weeks. 
        Returns amount of energy generated by the solar panel system, considering peak hours of irradiance '''

    print("Fetching Info, this might take upto 9 seconds ... ")
    globalHorizontalIrradiance = getCityInfo(city_name)
    panelEffeciency = 0.2                                                                                       # The panel effeicency of modern day solar panels range from 19 to 23 %
    AverageGHI = mean(list(globalHorizontalIrradiance.values())[:-1])
    AverageEnergybyTimeStep = AverageGHI*int(numberOfpanels)*totalSurfaceArea*panelEffeciency*6/24
    energy_generated = {}
    for date, ghi in globalHorizontalIrradiance.items():
        energy_generated[date] = int(ghi)*numberOfpanels*totalSurfaceArea*panelEffeciency
    
    plt.close()
    if OptToPlot == 'Y' or OptToPlot == 'y':
        days = list(energy_generated.keys())[:-1]
        energy = list(energy_generated.values())[:-1]
        plt.figure(figsize=(10, 6))  
        plt.plot(days, energy, marker='o')
        plt.xlabel('Day')
        plt.ylabel('Eneregy Generated')
        plt.title('Simulation of Energy Generated by the Solar Panel System over 30 Days')
        plt.xticks(rotation=45)  
        plt.grid(True)
        plt.savefig('Energy Generated by the Solar Panel System.png') 

    return AverageEnergybyTimeStep
